name: aqua_meal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.0
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.11
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  uuid: ^4.1.0
  image_picker: ^1.0.2
  provider: ^6.0.5
  path: ^1.8.2
  intl: ^0.18.1
  #Firebase Plugins
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8


  # google_fonts: ^2.3.2
  # curved_navigation_bar: ^1.0.3
  # shared_preferences: ^2.0.15
  # flutter_svg: ^1.1.4
  # url_launcher: ^6.1.5
  # flutter_rating_bar: ^4.0.1
  # cached_network_image: ^3.2.1
  # uuid: ^3.0.6
  # image_picker: ^0.8.5+3
  # provider: ^6.0.3
  # path: ^1.8.2
  # intl: ^0.17.0
  #Firebase Plugins
  # firebase_core: ^1.22.0
  # firebase_auth: ^3.9.0
  # cloud_firestore: ^3.4.8
  # firebase_storage: ^10.3.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
